###############################################################################
# Workflow runs on commits pushed to develop branch, and creates git tags
#
# When new commits are pushed to develop, this workflow:
# - checks for module images tagged with the sha of the last commit in the set
# - if all modules can be found, the a new git tag is created
###############################################################################
name: "Tag git"

on:
  push:
    branches:
      - main

jobs:
  tag:
    name: "Create git tag"
    runs-on: ubuntu-latest
    env:
      tooling_dir: ${{ github.workspace }}/../tooling
    steps:
      - name: "Cache tooling"
        uses: actions/cache@v2
        with:
          path: ${tooling_dir}
          key: ${{ runner.os }}-gitlab-clone-git-tag
      - name: "Setup tools"
        run: |
          mkdir -p ${tooling_dir}
          cd ${tooling_dir}
          wget --no-clobber https://github.com/miguelaferreira/semver_bash/archive/master.zip
          unzip master.zip
          cd semver_bash-master
          sudo mv semver.sh bump.sh /bin
          sudo chmod +x /bin/bump.sh
      - name: "Checkout sources"
        uses: actions/checkout@v2
      - name: "Bump version number"
        id: bump
        run: |
          version="$(cat ${version_file})"
          bump.sh "${old_version}" > ${version_file}
          echo "::set-output name=version-file::${version_file}"
          echo "::set-output name=version::${version}"
          echo "::set-output name=new-version::$(cat ${version_file})"
        env:
          version_file: VERSION
      - name: "Create tag"
        uses: EndBug/add-and-commit@v7.0.0
        with:
          message: "Increment version from '${{ steps.bump.outputs.version }}' to '${{ steps.bump.outputs.new-version }}'"
          default_author: github_actions
          tag: "${{ steps.bump.outputs.version }}"
          push: true
      - name: "Create bump commit"
        uses: EndBug/add-and-commit@v7.0.0
        with:
          message: "Increment version from '${{ steps.bump.outputs.version }}' to '${{ steps.bump.outputs.new-version }}'"
          add: ${{ steps.bump.outputs.version-file }}
          default_author: github_actions
          push: true
